export const emojis = {
    check: "✅",
    cross: "❌",
    pingPong: "🏓",
    robot: "🤖",
    music: "🎵",
    play: "▶️",
    pause: "⏸️",
    stop: "⏹️",
    speakerMute: "🔈",
    speakerLow: "🔉",
    speakerHigh: "🔊",
    nextTrack: "⏭️",
    memo: "📝",
    blackMediumSquare: "◼️",
    blueLargeSquare: "🟦",
    blackSmallSquare: "▪️",
    radioButton: "🔘",
    repeat: "🔁",
    repeatSingle: "🔂",
};
