package utils

const (
	EmojiCheck             = "✅"
	EmojiCross             = "❌"
	EmojiPingPong          = "🏓"
	EmojiRobot             = "🤖"
	EmojiMusic             = "🎵"
	EmojiPlay              = "▶️"
	EmojiPause             = "⏸️"
	EmojiStop              = "⏹️"
	EmojiSpeakerMute       = "🔈"
	EmojiSpeakerLow        = "🔉"
	EmojiSpeakerHigh       = "🔊"
	EmojiNextTrack         = "⏭️"
	EmojiMemo              = "📝"
	EmojiBlackMediumSquare = "◼️"
	EmojiBlueLargeSquare   = "🟦"
	EmojiBlackSmallSquare  = "▪️"
	EmojiRadioButton       = "🔘"
	EmojiRepeat            = "🔁"
	EmojiRepeatSingle      = "🔂"
	EmojiNsfw              = "🔞"
	EmojiSparkles          = "✨"
	EmojiFrown             = "☹️"
	EmojiUpArrow           = "⬆️"
	EmojiDownArrow         = "⬇️"
	EmojiMagnet            = "🧲"
	EmojiPackage           = "📦"
	EmojiCalendar          = "📅"
	EmojiPushPin           = "📌"
	EmojiId                = "🆔"
)
